parameters:
    vagrant_rest.response_listener.class:     Smalot\Vagrant\RestBundle\EventListener\ResponseListener

services:
    vagrant_rest.response_listener:
        class: "%vagrant_rest.response_listener.class%"
        tags:
            - { name: kernel.event_subscriber }
